// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oauhoiuaojpijmwiwjpe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9hdWhvaXVhb2pwaWptd2l3anBlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY3MjQwMzksImV4cCI6MjA3MjMwMDAzOX0.m_CQQyiMlBf9fc8CBR_4EHfJv6UstpQB4O35DVoc1t0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});